<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Comment;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NonUniqueResultException;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
    /**
     * @param $id
     * @return Comment
     * @throws NonUniqueResultException
     */
    public function addComment($id)
    {

        return $this->createQueryBuilder('comment')
            ->andWhere('comment.id = :id')
            ->innerjoin('comment.publicationId', 'fc')
            ->addSelect('fc')
            ->setParameter('id', $id)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
